
-- SQL CASE STUDY 1 Solutions - Retail Data Analysis


-- Q1 What is the total number of rows in each of the 3 tables in the database?

Select COUNT(*) ' Rows Count Of Transaction Table ' from Transactions
Select COUNT(*) ' Rows Count of Customer Table' from Customer
Select COUNT(*)'Rows Count of Product Cat Info Table' from prod_cat_info


-- Q2 What is the total number of transactions that have a return?

Select COUNT(total_amt) ' Count of Return Orders' from Transactions
Where total_amt<0


 

-- Q3 As you would have noticed the dates provided across the datasets are not in a correct format. As first steps, 
     --pls convert the date variables into valid date formats before proceeding ahead

-- I Converted The Tran_Date In Correct format at the time of importing the sheet using Edit Mapping --

-- Q4 What is the time range of the transaction data available for analysis?
    --Show the output in number of days, months and years simultaneously in different columns.

Select DATEDIFF(D,Min(tran_date),Max(Tran_Date)) 'Number Of Days' 
         , DATEDIFF(M,MIN(Tran_date),Max(Tran_date))'Number of Months' , 
              DATEDIFF(Y,MIN(Tran_date),Max(Tran_Date)) 'Number of Years' from Transactions

-- Q5 Which product category does the sub-category "DIY" belong to?

Select prod_cat from prod_cat_info
where prod_subcat = 'DIY'


-- DATA ANALYSIS -- 

-- Q1 Which channel is most frequently used for transactions?

Select Top 1 Store_type from Transactions
   Group by Store_type
      Order by COUNT(Transaction_id) Desc

	 

-- Q2 What is the count of Male and Female customers in the database?

Select Gender , COUNT(Customer_Id) ' Total Number Of Customers ' from Customer
    Group By Gender
	  having Gender <> ' ' -- I am using this having Because 2 Customers Gender is not Mentoined 
	
 
-- Q3 From which city do we have the maximum number of customers and how many? 

Select top 1 City_Code , COUNT(Customer_ID) ' Total Number of Customers' from Customer
    Group by city_code
	   Order by  COUNT(Customer_ID) DESC   -- So we have Max number of customers from City Code 3 and That is 595

-- Q4  How many sub-categories are there under the Books category?

Select Count(prod_subcat) 'Total Sub-Categories Under Books Category'   from prod_cat_info
   where prod_cat = 'Books'

-- Q5 What is the maximum quantity of products ever ordered?

Select MAX(Qty) 'Maximum Order Quantity' From Transactions

-- Q6 What is the net total revenue generated in categories Electronics and Books?


Select  T1.prod_cat ,  Sum(T2.total_amt)'Total Revenue Generated' from prod_cat_info T1 inner join Transactions T2 on T1.prod_cat_code = T2.prod_cat_code and T1.prod_sub_cat_code = T2.prod_subcat_code 
   Where T1.prod_cat IN ('Electronics','Books') 
      Group by prod_cat

-- Q7 How many customers have >10 transactions with us, excluding returns?

select cust_id ,Count(transaction_id) 'Transactions Count' from Transactions
    where total_amt > 0
	  Group by cust_id
	      having Count(transaction_id)>10
		 
-- Q8 What is the combined revenue earned from the "Electronics" & "Clothing" categories, from "Flagship stores"?

 Select Sum(T2.total_amt) 'Total Revenue Generated' from prod_cat_info T1 inner join Transactions T2 on T1.prod_cat_code = T2.prod_cat_code 
    Where T1.prod_cat IN ('Electronics','Clothing') and T2.Store_type = 'Flagship store'
     
	  
	     
 -- Q9 What is the total revenue generated from "Male" customers in "Electronics" category?  Output should display total revenue by prod sub-cat.

 Select T1.prod_subcat , Sum(T2.total_amt) 'Total Revenue' from prod_cat_info T1 inner join Transactions T2 on T1.prod_cat_code = T2.prod_cat_code and T1.prod_sub_cat_code = T2.prod_subcat_code 
      inner join Customer T3 on T3.customer_Id = T2.cust_id
        Where T3.Gender = 'M' and T1.prod_cat = 'Electronics'
		   Group by T1.prod_subcat

-- Q10  What is percentage of sales and returns by product sub category, display only top 5 sub categories in terms of sales?
 

select  top 5 P.prod_subcat,sum(case when t.total_amt < 0 then t.total_amt else 0 end)/ (sum(t.total_amt)) * 100 [Returms%],
		  				   sum(case when t.total_amt > 0 then t.total_amt else 0 end)/ (sum(t.total_amt)) * 100 [Sales%] 
from Transactions as T
INNER JOIN prod_cat_info as P ON T.prod_subcat_code = P.prod_sub_cat_code
group by P.prod_subcat
order by sum(total_amt) / (select sum(total_amt) from Transactions) desc


-- Q11 For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers
    --         in last 30 days of transactions from max transaction date available in the data?

	   		
SELECT SUM(t.total_amt) as Totall_revenue from Transactions T Inner join (select Max(tran_date) as Max_date from Transactions)  B
      on (t.tran_date between DATEADD(D,-30,B.Max_date) and B.Max_date)
	    left join Customer C on T.cust_id = C.customer_Id 
		  where YEAR(t.tran_date) - YEAR(C.DOB) between 25 and 35 
			
 
 			
		 

--Q12 Which product category has seen the max value of returns in the last 3 months of transactions?

Select top 1 p.prod_cat  
           from ( SELECT t.*, MAX(t.tran_date) OVER () as max_tran_date FROM Transactions t) t 
		      join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
	            where t.tran_date < t.max_tran_date 
	             and t.tran_date > Dateadd(M,-3,t.max_tran_date) 
	             and t.total_amt < 0 
	              group by p.prod_cat
				   Order by count(t.total_amt) desc
	  
--Q13  Which store-type sells the maximum products, by value of sales amount and by quantity sold?

select top 1  Store_type   from Transactions 
   group by Store_type
    order by   (sum(total_amt) / COUNT(qty))  desc
    

	  
--Q14  What are the categories for which average revenue is above the overall average 

select p.prod_cat  from Transactions t
     Join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
      group by p.prod_cat
       having  AVG(t.total_amt)  > (Select AVG(total_amt) from Transactions)


 
     
--Q15 Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold

select p.prod_subcat, AVG(total_amt)'Average of Sales by Sub-Category'  , SUM(total_amt)'Total of Sales by Sub-Category'  from Transactions t join prod_cat_info p 
       on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
           where  p.prod_cat_code =  ANY((select  top 5 p.prod_cat_code  from Transactions t join prod_cat_info p 
                                             on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
	                                           group by p.prod_cat_code
	                                             order by Count(t.qty) desc ))
	       group by p.prod_subcat

 
